Automarket/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Automarket.DAL.Interfaces;
using Automarket.Domain.Entity;
using Automarket.Domain.Response;
using Automarket.Domain.ViewModels.Car;
using Automarket.Service.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Automarket.Controllers
{
    public class CarController : Controller
    {
        //private readonly ICarRepository _carRepository;

        //public CarController(ICarRepository carRepository)
        //{
        //    _carRepository = carRepository;
        //}

        private readonly ICarService _carService;

        public CarController(ICarService carService)
        {
            _carService = carService;
        }

        [HttpGet]
        public async Task<IActionResult> GetCars()
        {
            //var response = await _carRepository.Select();
            //var response1 = await _carRepository.GetByName("BMW X5");
            //var response2 = await _carRepository.Get(4);

            //var car = new Car()
            //{
            //    Name = "Vaz 2114",
            //    Model = "VAZ",
            //    Speed = 140,
            //    Price = 150000,
            //    Desctiption = "Test",
            //    DateCreate = DateTime.Now
            //};

            //await _carRepository.Create(car);
            //await _carRepository.Delete(car);

            var response = await _carService.GetCars();
            //if (response.StatusCode == Domain.Enum.StatusCode.OK)
            //{
            //    return View(response.Data);
            //}
            //return RedirectToAction("Error");

            return View(response.Data);
        }

        //[HttpGet]
        //public async Task<IActionResult> GetCar(int id)
        //{
        //    var response = await _carService.GetCar(id);
        //    if (response.StatusCode == Domain.Enum.StatusCode.OK)
        //    {
        //        return View(response.Data);
        //    }

        //    return RedirectToAction("Error");
        //}

        [HttpGet]
        public async Task<ActionResult> GetCar(int id, bool isJson)
        {
            var response = await _carService.GetCar(id);
            if (isJson)
            {
                return Json(response.Data);
            }
            return PartialView("GetCar", response.Data);
        }

        [HttpPost]
        public async Task<IActionResult> GetCar(string name, int page = 1, int pageSize = 5)
        {
            var response = await _carService.GetCar(name);
            return Json(response.Data);
        }

        [HttpPost]
        public JsonResult GetTypes()
        {
            var types = _carService.GetTypes();
            return Json(types.Data);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _carService.DeleteCar(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return RedirectToAction("GetCars");
            }

            return RedirectToAction("Error");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Save(int id)
        {
            if (id == 0)
            {
                return View();
            }

            var response = await _carService.GetCar(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }

            return RedirectToAction("Error");
        }

        [HttpPost]
        public async Task<IActionResult> Save(CarViewModel model)
        {
            ModelState.Remove("DateCreate");
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                {
                    byte[] imageData;
                    using (var binaryReader = new BinaryReader(model.Avatar.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)model.Avatar.Length);
                    }
                    await _carService.CreateCar(model, imageData);
                }
                else
                {
                    await _carService.Edit(model.Id, model);
                }

                return RedirectToAction("GetCars");
            }

            return View();
        }

        public IActionResult Compare() => PartialView();
    }
}

Automarket/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Automarket.Domain.ViewModels.Order;
using Automarket.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Automarket.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        [HttpGet]
        public IActionResult CreateOrder(long id)
        {
            var orderModel = new CreateOrderViewModel()
            {
                CarId = id,
                Login = User.Identity?.Name,
                Quantity = 0
            };
            return View(orderModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrder(CreateOrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _orderService.Create(model);
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    return Json(new { description = response.Description });
                }
            }
            return StatusCode(StatusCodes.Status500InternalServerError);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _orderService.Delete(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return RedirectToAction("Index", "Home");
            }
            return View("Error", $"{response.Description}");
        }
    }
}

Automarket/Views/Car/Compare.cshtml
<div class="row">
    <div class="col">
        <select class="form-control" id="firstCarId"></select>
    </div>
    <div class="col">
        <select class="form-control" id="secondCarId"></select>
    </div>
</div>

<div style="padding: 10px;"></div>

<div class="row">
    <div class="col-md-6">
        <div class="card-body">
            <h5 class="card-title" id="firstCardTitleId"></h5>
            <p class="card-text" id="firstCardDescId"></p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item" id="firstCardSpeedId"></li>
            <li class="list-group-item" id="firstCardPriceId"></li>
            <li class="list-group-item" id="firstCardModelId"></li>
            <li class="list-group-item" id="firstCardDateCreateId"></li>
        </ul>
    </div>
    <div class="col-md-6">
        <div class="card-body">
            <h5 class="card-title" id="secondCardTitleId"></h5>
            <p class="card-text" id="secondCardDescId"></p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item" id="secondCardSpeedId"></li>
            <li class="list-group-item" id="secondCardPriceId"></li>
            <li class="list-group-item" id="secondCardModelId"></li>
            <li class="list-group-item" id="secondCardDateCreateId"></li>
        </ul>
    </div>
</div>

<div style="padding: 10px;"></div>

<div class="text-white bg-secondary" id="warningCardId">
    <div class="bg-secondary card-header text-white">
        Предупреждение
    </div>
    <div class="card-body">
        <blockquote class="blockquote mb-0">
            <p id="warningId"></p>
        </blockquote>
    </div>
</div>

<div style="padding: 10px;"></div>

<div id="resultCardId">
    <div class="bg-secondary card-header text-white">
        Результат
    </div>
    <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item" id="resultSpeedId"></li>
            <li class="list-group-item" id="resultPriceId"></li>
        </ul>
    </div>
</div>

<script src="~/lib/select2/js/select2.full.min.js"></script>
<script>
$(document).ready(function () {

    $('#firstCardId').hide();
    $('#secondCardId').hide();
    $('#warningCardId').hide();
    $('#resultCardId').hide();

    let firstCar = null;
    let secondCar = null;

    $('#firstCarId, #secondCarId').select2({
       placeholder: "Выберите машину",
       minimumInputLength: 2,
       allowClear: true,
       ajax: {
            type: "POST",
            url: "@Url.Action("GetCar", "Car")",
            dataType: "json",
            data: function (params) {
                var query = {
                    term: params.term,
                    page: params.page || 1,
                    pageSize: params.pageSize || 5
                };
                return query;
            },
            processResults: function (result) {
                return {
                    results: $.map(result, function (val, index) {
                        return {
                            id: index,
                            text: val
                        };
                    }),
                };
            }
        }
    });

    function fillData(val, cardId){
        if (cardId === 'firstCardId'){
            $('#firstCardId').show();
            $('#firstCardTitleId')[0].innerText = 'Название: ' + val.name;
            $('#firstCardDescId')[0].innerText = 'Описание: ' + val.description;
            $('#firstCardSpeedId')[0].innerText = 'Скорость: ' + val.speed + ' км/ч';
            $('#firstCardPriceId')[0].innerText = 'Стоимость: ' + val.price + ' ₽';
            $('#firstCardModelId')[0].innerText = 'Модель: ' + val.model;
            $('#firstCardDateCreateId')[0].innerText = 'Дата создания: ' + val.dateCreate;
        } else {
            $('#secondCarId').show();
            $('#secondCardTitleId')[0].innerText = 'Название: ' + val.name;
            $('#secondCardDescId')[0].innerText = 'Описание: ' + val.description;
            $('#secondCardSpeedId')[0].innerText = 'Скорость: ' + val.speed + ' км/ч';
            $('#secondCardPriceId')[0].innerText = 'Стоимость: ' + val.price + ' ₽';
            $('#secondCardModelId')[0].innerText = 'Модель: ' + val.model;
            $('#secondCardDateCreateId')[0].innerText = 'Дата создания: ' + val.dateCreate;
        }
        compareCars();
    }


    $("#secondCarId").on("change", function(){
        const id = this.value;
        if (id === "") return;
        $.get("/Car/GetCar", { id : id, isJson : true }, function(data) {
            secondCar = data;
            fillData(secondCar, "secondCarId");
        });
    });

    $("#firstCarId").on("change", function(){
        const id = this.value;
        if (id === "") return;
        $.get("/Car/GetCar", { id : id, isJson : true }, function(data) {
            firstCar = data;
            fillData(firstCar, "firstCardId");
        });
    });

    function compareCars(){
        if (firstCar === null) {
            $('#warningId')[0].innerText = 'Вы не выбрали первый автомобиль';
            $('#warningCardId').show();
            return;
        }

        if (secondCar === null) {
            $('#warningId')[0].innerText = 'Вы не выбрали второй автомобиль';
            $('#warningCardId').show();
            return;
        }

        var speed = $('#resultSpeedId')[0];
        if (firstCar.speed > secondCar.speed) {
            speed.innerText = 'Скорость ' + firstCar.name + ' выше, чем у ' + secondCar.name;
        } else if (firstCar.speed === secondCar.speed) {
            speed.innerText = 'Скорость ' + secondCar.name + ' и ' + firstCar.name + ' равны';
        } else {
            speed.innerText = 'Скорость ' + secondCar.name + ' выше, чем у ' + firstCar.name;
        }

        var price = $('#resultPriceId')[0];
        if (firstCar.price > secondCar.price) {
            price.innerText = 'Стоимость ' + firstCar.name + ' выше, чем у ' + secondCar.name;
        } else if (firstCar.price === secondCar.price) {
            price.innerText = 'Стоимость ' + firstCar.name + ' и ' + secondCar.name + ' равны';
        } else {
           price.innerText = 'Стоимость ' + firstCar.name + ' выше, чем у ' + secondCar.name;
        }

        $('#resultCardId').show();
        $('#warningCardId').hide();
    }
  });
</script>

Automarket/Views/Car/GetCar.cshtml
@model CarViewModel
@*@{
        ViewBag.Title = "title";
        Layout = "_Layout";
    }

    <div style="padding: 10px;"></div>
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="https://images.wallpaperscraft.ru/image/single/mercedes_benz_s_class_w222_112850_800x600.jpg"
                     class="img-fluid rounded-start rounded" alt="@Model?.Name">
            </div>
            <div class="col-md-4">
                <div class="card-body">
                    <h5 class="card-title text-center">@Model?.Name</h5>
                    <p class="card-text"><b>Description: </b>@Model?.Desctiption</p>
                    <p class="card-text"><b>Price: </b>@Model?.Price $</p>
                    <p class="card-text"><b>Type: </b>@Model?.TypeCar</p>
                    <p class="card-text"><b>Model: </b>@Model?.Model</p>
                    <p class="card-text"><small class="text-muted">Date created - @Model?.DateCreate</small></p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card-body">
                    <p class="card-text"><b>Description: </b>@Model?.Desctiption</p>
                </div>
            </div>
        </div>
    </div>*@

<form>
    <div class="row">
        <div class="col-md-12">
            <img src="data:image/jpeg;base64,@Convert.ToBase64String(Model?.Image ?? Array.Empty<byte>())"
                 class="img-fluid rounded-start rounded">
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-4">
            <label asp-for="@Model.Name" class="col-form-label"></label>
            <input type="text" class="form-control" asp-for="@Model.Name">
        </div>
        <div class="form-group col-md-4">
            <label asp-for="@Model.Model" class="col-form-label"></label>
            <input class="form-control" asp-for="@Model.Model" />
        </div>
        <div class="form-group col-md-4">
            <label asp-for="@Model.Price" class="col-form-label"></label>
            <input type="text" class="form-control" asp-for="@Model.Price" />
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-12">
            <label asp-for="@Model.Desctiption" class="col-form-label"></label>
            <textarea type="text" class="form-control" asp-for="@Model.Desctiption"></textarea>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="@Model.TypeCar" class="col-form-label"></label>
            <select class="form-control" id="carTypeId2">
                <option value="@Model.TypeCar">@Model.TypeCar</option>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="@Model.DateCreate" class="col-form-label"></label>
            <input class="form-control" asp-for="@Model.DateCreate" />
        </div>
    </div>
</form>

<style>
    label {
        color: black;
    }
</style>

<script src="~/lib/select2/js/select2.full.min.js"></script>
<script>
$('#carTypeId2').select2({
   placeholder: "Выберите тип",
   minimumInputLength: 0,
   allowClear: true,
   ajax: {
        type: "POST",
        url: "@Url.Action("GetTypes", "Car")",
        dataType: "json",
        processResults: function (result) {
            return {
                results: $.map(result, function (val, index) {
                    return {
                        id: index,
                        text: val
                    };
                }),
            };
        }
    }
});
</script>

Automarket/Views/Car/GetCars.cshtml
@using Automarket.Domain.ViewModels.Car
@model List<Automarket.Domain.Entity.Car>

@{
    ViewBag.Title = "Список автомобилей";
    Layout = "_Layout";
}

@{
    var cardStyle = "col-md-12";
    if (Model != null)
    {
        switch (Model.Count)
        {
            case 2:
                cardStyle = "col-md-6";
                break;
            case 3:
                cardStyle = "col-md-4";
                break;
        }
    }
}

<style>
    .card-buttons-group {
        text-align: right;
        padding: 10px;
    }
</style>

<div class="card col-md-12" style="margin: 10px;">
    <div class="card-buttons-group">
        <button class='btn btn-primary' id='compareBtnId'>Comparison</button>
        @if (User.IsInRole("Admin"))
        {
            <button class='btn btn-success' id='addCarId'>Add</button>
        }
    </div>
</div>

<div style="padding: 10px;"></div>
@if (Model == null)
{
    <div class="card col-md-12">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="https://images.wallpaperscraft.ru/image/single/bmw_fary_podsvetka_137326_1280x720.jpg"
                     class="img-fluid rounded-start rounded">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title text-center">The list of cars is empty :(</h5>
                    <p class="card-text">
                        The list will be updated later, do not worry
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div style="padding: 10px;"></div>
    <div class="card text-center">
        <div class="card-header">
            <ul class="nav nav-pills card-header-pills">
                <li class="nav-item">
                    <a class="nav-link active" href="#">Active</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
}
else
{
    <div class="row">
        @foreach (var car in Model)
        {
            <div class="row row-cols-1 @cardStyle text-center">
                <div class="col" style="padding: 10px;">
                    <div class="card">
                        <img src="data:image/jpeg;base64,@Convert.ToBase64String(car?.Avatar ?? Array.Empty<byte>())" alt="@car.Name" />
                        <div class="card-body">
                            <h5 class="card-title">Name: @car.Name</h5>
                            <p class="card-text">Short description: @car.Desctiption ...</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Speed: @car.Speed km/h</li>
                            <li class="list-group-item">Price: @car.Price $</li>
                            <li class="list-group-item">Model: @car.Model</li>
                        </ul>
                        <div class="card-body">
                            <button class="btn btn-primary" onclick="openModal({ url: '/Car/GetCar', data: '@car.Id' })"
                                    data-toggle="ajax-modal" data-target="Modal">
                                Открыть
                            </button>
                            @if (User.IsInRole("Admin"))
                            {
                                <a asp-controller="Car" asp-action="Delete" asp-route-id="@car.Id" class="btn btn-danger">Delete</a>
                            }
                            <a asp-controller="Order" asp-action="CreateOrder" asp-route-id="@car.Id" class="btn btn-success">Into a basket</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}

@section pageScripts {

    <script src="~/js/modal.js"></script>
    <script>
       let modal = $('#modalWhButtons');

       $('#compareBtnId').on('click', function (){
           $.ajax({
               type: 'GET',
               url : '@Url.Action("Compare")',
               success: function (response) {
                   $('.modal-dialog').addClass("modal-lg");
                   modal.find(".modal-body").html(response);
                   modal.modal('show')
               }
           });
       });

       $(".btn-close").click(function(){
            modal.modal('hide');
       });

       $('#addCarId').on('click', function () {
           $.ajax({
              type: 'GET',
              url : '/Car/Save',
              success: function (response) {
                  $('.modal-dialog').removeClass("modal-lg");
                  modal.find(".modal-body").html(response);
                  modal.modal('show')
              },
              failure: function () {
                modal.modal('hide')
              },
              error: function (response) {
                  alert(response.responseText);
              }
          });
       });

    </script>
}

Automarket/Views/Car/Save.cshtml
@model Automarket.Domain.ViewModels.Car.CarViewModel
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

@{
    var textTitle = Model?.Id == 0 ? "Changing data" : "Adding Data";
}

<div style="padding: 10px;"></div>
<div class="col-md-12">
    <div class="card-body">
        <div class="card card-outline-secondary" style="background-color: white">
            <div class="card-header">
                <h3 class="mb-0 text-center ParagraphHome">@textTitle</h3>
            </div>
            <div class="card-body">
                <form asp-action="Save" enctype="multipart/form-data">
                    <input asp-for="Id" hidden />
                    <div asp-validation-summary="All" style="font-size:23px; font-family:Impact, serif" class="text-danger text-center"></div>
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" type="text">
                    </div>
                    <div class="form-group">
                        <label asp-for="Model"></label>
                        <input asp-for="Model" class="form-control" type="text">
                    </div>
                    <div class="form-group">
                        <label asp-for="Speed"></label>
                        <input asp-for="Speed" class="form-control" type="text">
                    </div>
                    <div class="form-group">
                        <label asp-for="Desctiption"></label>
                        <textarea asp-for="Desctiption" class="form-control"></textarea>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text">₽</span>
                        <input asp-for="Price" type="text" class="form-control">
                        <span class="input-group-text">.00</span>
                    </div>
                    <div class="form-group">
                        <select class="form-control" asp-for="TypeCar" id="carTypeId"></select>
                    </div>
                    <div class="input-group mb-3">
                        <input asp-for="Avatar" class="form-control" type="file">
                    </div>
                    <button class="btn btn-primary btn-lg float-right" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>